import { LanguageModel } from './translations';

export const LangTh: LanguageModel = {
    Lang: 'th',
    Language: 'ไทย',
    License: 'ทะเบียน',
    LicenseSelect: 'เลือกทะเบียน',
    Status: 'สถานะ',
    Speed: 'ความเร็ว',
    Date: 'วันที่',
    Day: 'วัน',
    Address: 'สถานที่',
    Realtime: 'ปัจจุบัน',
    History: 'ย้อนหลัง',
    Report: 'รายงาน',
    Total: 'สรุป',
    Length: 'ระยะทาง',
    Km: 'กม.',
    KmH: 'กม/ชม',
    Runningtime: 'เวลาวิ่ง',
    Stoppingtime: 'เวลาหยุด',
    Parkingtime: 'เวลาจอด',
    ConnectionRefused: 'การเชื่อมต่อขัดข้อง กรุณาลองใหม่ภายหลัง',
    PleaseSelect: 'กรุณาเลือกข้อมูลที่ต้องการค้นหาให้ถูกต้อง',
    ErrorMassage: 'ข้อผิดพลาด',
    Ok: 'ตกลง',
    Loading: 'กำลังโหลดข้อมูล...',
    DelayExceeded: 'การเชื่อมต่อขัดข้อง',
    Overspeedtimes: 'ขับเร็ว(ครั้ง)',
    Overspeedmax: 'ความเร็ว(สูงสุด)',
    Idletimes: 'หยุดรถ(ครั้ง)',
    Idletotal: 'หยุดรถ(เวลา)',
    Parktimes: 'จอดรถ(ครั้ง)',
    Parktotal: 'จอดรถ(เวลา)',
    TotalUsag: 'เวลาใช้งานรถ',
    TotalDis: 'ระยะทาง',
    Ig: 'สวิทช์กุญแจ',
    Reportlist: 'รายงาน',
    StartDate: 'วันที่เริ่ม',
    EndDate: 'วันที่ถึง',
    Period: 'ระยะเวลา',
    Search: 'ค้นหา',
    Idle: 'หยุดรถ',
    Overspeed: 'ขับเร็ว',
    Park: 'จอดรถ',
    On: 'เปิด',
    Off: 'ปิด',
    All: 'ทั้งหมด',
    Logout: 'ออกจากระบบ',
    Login: 'เข้าสู่ระบบ',
    Running: 'วิ่ง',
    Idling: 'หยุด',
    IgOff: 'ปิดสวิทช์กุญแจ',
    IgOn: 'เปิดสวิทช์กุญแจ',
    Parking: 'จอด',
    ParkingLost: 'จอด(ไม่มี gps)',
    IgOnLost: 'เปิดสวิทช์กุญแจ(ไม่มี gps)',
    IgOffLost: 'ปิดสวิทช์กุญแจ(ไม่มี gps)',
    RunningLost: 'วิ่ง(ไม่มี gps)',
    PtoOff: 'เปิดประตู',
    PtoOn: 'ปิดประตู',
    Unplug: 'ถอดปลั๊ก gps',
    PlugIn: 'เสียบปลั๊ก gps',
    BoxReset: 'รีเซ็ดกล่อง gps',
    IdlingStart: 'หยุด',
    ParkRunning: 'โดนลาก',
    NotFound: 'ไม่พบข้อมูล',
    Back: 'กลับ',
    More: 'เพิ่มเติม',
    Translation: 'แปลภาษา',
    ChangeLanguage: 'เปลี่ยนภาษา',
    ChangePassword: 'เปลี่ยนรหัสผ่าน',
    Close: 'ยกเลิก',
    Done: 'เสร็จสิ้น',
    ReNewPassword: 'ยืนยันรหัสผ่าน',
    NewPassword: 'รหัสผ่านใหม่',
    CurrentPassword: 'รหัสผ่านปัจจุบัน',
    Username: 'ผู้ใช้',
    Match: 'ถูกต้อง',
    DoNot: 'ไม่',
    Password: 'รหัสผ่าน',
    Other: 'อื่นๆ',
    Setting: 'ตั้งค่า',
    VehicleSetting: 'ตั้งค่ารถ',
    Vehicle: 'รถ',
    ShowDaily: 'ดูรายวัน',
    Chart: 'กราฟ',
    ReportStatus: 'สถานะ (นาที)',
    ReportDailyStatus: 'สถานะรายวัน (นาที)',
    ReportDistanceDaily: 'ระยะทางรายวัน (กม.)',
    ReportOverSpeed: 'ขับเร็ว (ครั้ง)',
    Next: 'ถัดไป',
    CheckAll: 'เลือกทั้งหมด',
    UnCheckAll: 'ยกเลิกทั้งหมด',
    SettingReportDetail: 'รายละเอียดการตั้งค่า',
    OverSpeedMax: 'ความเร็วสูงสุด',
    OverSpeedTimes: 'ความเร็วเกิน (นาที)',
    IdleTimes: 'หยุดรถเกินกำหนด (นาที)',
    ParkTimes: 'จอดรถเกินกำหนด (นาที)',
    Save: 'ตกลง',
    Custom: 'กำหนดเอง',
    Temp1: 'อุณหภูมิ 1',
    Temp2: 'อุณหภูมิ 2',
    HiddenAndShowTemp: 'แสดง/ซ่อน อุณหภูมิ',
    SelectGroup: 'เลือกกลุ่ม',
    Station: 'สถานี',
    StationName: 'ชื่อสถานี',
    InDateTime: 'เวลาเข้า',
    OutDateTime: 'เวลาถึง',
    InTemp: 'อุณหภูมิเข้า',
    OutTemp: 'อุณหภูมิออก',
    RunTimeMax: 'เวลาขับรถต่อเนื่องสูงสุด',
    SureLogOut: 'คุณแน่ใจหรือว่าต้องการออกจากระบบ',
    And: 'และอีก',
    Help: 'การใช้งาน',
    Remember: 'เข้าสู่ระบบตลอด',
    Up: 'อัพเดท'
};