import { LanguageModel } from './translations';

export const LangEn: LanguageModel = {
    Lang: 'en',
    Language: 'English',
    License: 'License',
    LicenseSelect: 'License select',
    Status: 'Status',
    Speed: 'Speed',
    Date: 'Date',
    Day: 'Day',
    Address: 'Address',
    Realtime: 'Realtime',
    History: 'History',
    Report: 'Report',
    Total: 'Summary',
    Length: 'Distance',
    KmH: 'Km/H',
    Km: 'Km.',
    Runningtime: 'Running time',
    Stoppingtime: 'Stopping time',
    Parkingtime: 'Parking time',
    ConnectionRefused: 'Connection Refused',
    PleaseSelect: 'Please select the desired data',
    ErrorMassage: 'Error Massage',
    Ok: 'Ok',
    Loading: 'Loading...',
    DelayExceeded: 'Delay exceeded',
    Overspeedtimes: 'Overspeed(times)',
    Overspeedmax: 'Overspeed(max)',
    Idletimes: 'Idle(times)',
    Idletotal: 'Idle(total)',
    Parktimes: 'Park(times)',
    Parktotal: 'Park(total)',
    TotalUsag: 'TotalUsag',
    TotalDis: 'TotalDis',
    Ig: 'Ig',
    Reportlist: 'Report list',
    StartDate: 'StartDate',
    EndDate: 'EndDate',
    Period: 'Period',
    Search: 'Search',
    Idle: 'Idle',
    Overspeed: 'Overspeed',
    Park: 'Park',
    On: 'On',
    Off: 'Off',
    All: 'All',
    Logout: 'Logout',
    Login: 'Login',
    Running: 'Running',
    Idling: 'Idling',
    IgOff: 'IgOff',
    IgOn: 'IgOn',
    Parking: 'Parking',
    ParkingLost: 'ParkingLost',
    IgOnLost: 'IgOnLost',
    IgOffLost: 'IgOffLost',
    RunningLost: 'RunningLost',
    PtoOff: 'PtoOff',
    PtoOn: 'PtoOn',
    Unplug: 'Unplug',
    PlugIn: 'PlugIn',
    BoxReset: 'BoxReset',
    IdlingStart: 'IdlingStart',
    ParkRunning: 'ParkRunning',
    NotFound: 'Not Found',
    Back: 'Back',
    More: 'More',
    Translation: 'Translation',
    ChangeLanguage: 'Change language',
    ChangePassword: 'Change password',
    Close: 'Close',
    Done: 'Done',
    ReNewPassword: 'Confirm password',
    NewPassword: 'New password',
    CurrentPassword: 'Old password',
    Username: 'Username',
    Match: ' match',
    DoNot: ' do not',
    Password: 'Password',
    Other: 'Other',
    Setting: 'Setting',
    VehicleSetting: 'Vehicle setting',
    Vehicle: 'Vehicle',
    ShowDaily: 'Daily',
    Chart: 'Chart',
    ReportStatus: 'Status (min)',
    ReportDailyStatus: 'Daily status (min)',
    ReportDistanceDaily: 'Distance status (km.)',
    ReportOverSpeed: 'Over speed (time)',
    Next: 'Next',
    CheckAll: 'Select all',
    UnCheckAll: 'Clear',
    SettingReportDetail: 'SettingReport Detail',
    OverSpeedMax: 'Maximum speed',
    OverSpeedTimes: 'Overspeed duration limit',
    IdleTimes: 'Stop duration limit',
    ParkTimes: 'Park  duration limit',
    Save: 'Save',
    Custom: 'Custom',
    Temp1: 'Temp1',
    Temp2: 'Temp2',
    HiddenAndShowTemp:'Show/Hidden Temp',
    SelectGroup: 'Select group',
    Station: 'Station',
    StationName: 'Station name',
    InDateTime: 'In time',
    OutDateTime: 'Out time',
    InTemp: 'In temperature',
    OutTemp: 'Out temperature',
    RunTimeMax: 'Run time max',
    SureLogOut: 'Are you sure you want to log out?',
    And: 'And',
    Help: 'Help',
    Remember: 'Remember',
    Up: 'Up'
};